= The OMHTK library

'**O**ne **M**ore **H**andy **T**ool**K**it'

A bunch of low-level utilities that developers keep re-coding in many applications. In an ideal world this package should be replaced by state-of-the-art well designed universal libraries dealing with all the little problems appearing in this code. Unfortunately, developers keep reinventing the wheel, either because the existing wheel is poorly documented, or there are too many versions of it, or it is hidden in a crowd of other classes one doesnt need - so why import the whole mess? We tried to keep it light-weight and with as few dependencies as possible. If you think that one of the classes in there can be advantageously replaced by an existing one, please tell us and we will remove it.

Contains classes for:

* manipulation of jar files
* random number generation
* management of preference files
* arrays of strings and numbers
* additional list types
* lazy initialisation of classes
* version management
* code generation
* basic interfaces for use in any application
* intervals, duples, tuples, statistics basic classes
* integer range, number ranges, string manipulation (again!) file manipulation, date and time...

see the link:./omhtk/javadoc/index.html[javadoc]

TODO: find a way to display the above as formatted html and not a raw file